trigger:
  - main

#pool:
#  vmImage: ubuntu-latest
pool:
  name: Default  # Use the name of your agent pool
  demands:
    - agent.name -equals Self Hosted # Replace with the name of your Agent

steps:
  - task: NodeTool@0
    displayName: 'Install Node.js'
    inputs:
      versionSpec: '18.x'

  - checkout: self

  - script: |
      cd backend
      npm install
      cd ..
      cd frontend
      npm install
    displayName: 'Install Dependencies'

  - script: |
      cd frontend
      npm run build
      cd ..
    displayName: 'Build React App'

  - task: ArchiveFiles@2
    displayName: 'Archive Files'
    inputs:
      rootFolderOrFile: 'frontend/build'
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifacts'
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'drop'
      publishLocation: 'container'

  - task: AzureWebApp@1
    displayName: 'Deploy to Azure Web App'
    inputs:
      azureSubscription: 'MyAzureSubscription'
      appName: 'swear-jar-app'
      package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
      appType: 'webApp'
