trigger:
  - main

pool:
  name: Self Hosted
  demands:
    - agent.name -equals DESKTOP-F638SF0

steps:
  - checkout: self

  - script: |
      cd backend
      npm install --legacy-peer-deps
      cd ..
      tar -czvf backend.tar.gz backend
      cd frontend
      npm install --legacy-peer-deps
    displayName: 'Install Dependencies'

  - script: |
      cd frontend
      where.exe react-scripts || npm install react-scripts --save-dev
    displayName: 'Ensure react-scripts is installed'

  - script: |
      cd frontend
      npx react-scripts build
    displayName: 'Build React App'

  - task: ArchiveFiles@2
    displayName: 'Archive Backend Files'
    inputs:
      rootFolderOrFile: 'backend/'
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/backend.zip'
      replaceExistingArchive: true


  - task: ArchiveFiles@2
    displayName: 'Archive Frontend Files'
    inputs:
      rootFolderOrFile: 'frontend/build/*'
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/frontend.zip'
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Frontend Artifacts'
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/frontend.zip' # match file
      artifactName: 'frontend'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Backend Artifacts'
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/backend.zip' # match file
      artifactName: 'backend'

  - task: AzureWebApp@1
    displayName: 'Deploy Frontend to Azure Web App'
    inputs:
      azureSubscription: 'MyAzureSubscription'
      appName: 'swear-jar-app'
      package: '$(Build.ArtifactStagingDirectory)/frontend.zip'
      appType: 'webApp'
      deploymentMethod: zipDeploy

# Deploy Back end
  - task: AzureWebApp@1
    displayName: 'Deploy Backend API Azure App Services'
    inputs: # must match the above and be precise
      azureSubscription: 'MyAzureSubscription'
      appName: 'swear-jar-app-backend' # make sure the web app matches to backend
      package: '$(Build.ArtifactStagingDirectory)/backend.zip' # this is important
      appType: webApp # make the approprate choice
      deploymentMethod: zipDeploy
      startupCommand: 'npm start'