trigger:
  - main

pool:
  name: Self Hosted  # Use the name of your agent pool
  demands:
    - agent.name -equals DESKTOP-F638SF0 # Replace with the name of your Agent

steps:
  - checkout: self

  - script: |
      cd backend
      npm install --force
      cd ..
      cd frontend
      npm install --force
    displayName: 'Install Dependencies'

  - script: |
      cd frontend
      echo "Current directory: %cd%"  # Updated: Windows command for current directory
      dir  # Updated: Windows command to list files
      echo "Contents of node_modules\.bin:"  # Added escaped backslash
      dir node_modules\.bin  # Updated: Windows command to list files in directory
      echo "Running Build"
      npm run build
    displayName: 'Build React App'

  - task: ArchiveFiles@2
    displayName: 'Archive Files'
    inputs:
      rootFolderOrFile: 'frontend/bio/build'
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifacts'
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'drop'
      publishLocation: 'container'

  - task: AzureWebApp@1
    displayName: 'Deploy to Azure Web App'
    inputs:
      azureSubscription: 'MyAzureSubscription'
      appName: 'swear-jar-app'
      package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
      appType: 'webApp'
