trigger:
  - main

pool:
  name: Self Hosted  # Your agent pool
  demands:
    - agent.name -equals DESKTOP-F638SF0  # Your machine's agent name

steps:
  - checkout: self

  - script: |
      cd backend
      npm ci
      cd ../frontend
      npm ci
    displayName: 'Install Dependencies'

  - script: |
      npm run build
    displayName: 'Build React App'
    workingDirectory: frontend  # Ensure correct directory

  - task: ArchiveFiles@2
    displayName: 'Archive Files'
    inputs:
      rootFolderOrFile: 'frontend/build'  # Ensure correct build folder
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifacts'
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'drop'
      publishLocation: 'container'

  - task: AzureWebApp@1
    displayName: 'Deploy to Azure Web App'
    inputs:
      azureSubscription: 'MyAzureSubscription'
      appName: 'swear-jar-app'
      package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
      appType: 'webApp'
